# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        module load Anaconda3
        source activate /well/woolrich/users/yaq921/.conda/envs/job_run
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Restore cache data
      id: cache-data-restore
      uses: actions/cache/restore@v3
      with:
        path: data
        key: ${{ runner.os }}-data-cichy-1 # key to identify the cache
    - name: Download data
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python scripts/cichy_download.py 1
        python scripts/cichy_preproc_epoched.py 1
        python scripts/cichy92_download.py 1
        python scripts/cichy92_preproc_epoched.py 1
        rm -r data/scratch
        rm -r data/cichy92/scratch
    - name: Cache data
      uses: actions/cache/save@v3
      with:
        path: data
        key: ${{ steps.cahce-data-restore.outputs.cache-primary-key }} # key to identify the cache

    - name: args_lda_pca_fe_multiclass
      run: |
        cp examples/args_lda_pca_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_pca_fe_multiclass.py
    - name: args_lda_pca_sw_multiclass
      run: |
        cp examples/args_lda_pca_sw_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_pca_sw_multiclass.py
    - name: args_cichy92_lda_pca_fe_multiclass
      run: |
        cp examples/args_cichy92_lda_pca_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_cichy92_lda_pca_fe_multiclass.py
    - name: args_nn
      run: |
        cp examples/args_nn.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_nn.py
    - name: args_lda_nn_chn_multiclass
      run: |
        cp examples/args_lda_nn_chn_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_chn_multiclass.py
    - name: args_lda_nn_fe_multiclass
      run: |
        cp examples/args_lda_nn_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass.py
    - name: args_lda_nn_sw_multiclass
      run: |
        cp examples/args_lda_nn_sw_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_sw_multiclass.py
    - name: args_lda_nn_fe_multiclass2pairwise
      run: |
        cp examples/args_lda_nn_fe_multiclass2pairwise.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass2pairwise.py
    - name: args_lda_nn_fe_multiclass_spatialPFI
      run: |
        cp examples/args_lda_nn_fe_multiclass_spatialPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spatialPFI.py
    - name: args_lda_nn_fe_multiclass_spatiotemporal
      run: |
        cp examples/args_lda_nn_fe_multiclass_spatiotemporal.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spatiotemporal.py
    - name: args_lda_nn_fe_multiclass_spectralPFI
      run: |
        cp examples/args_lda_nn_fe_multiclass_spectralPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spectralPFI.py
    - name: args_lda_nn_fe_multiclass_temporalPFI
      run: |
        cp examples/args_lda_nn_fe_multiclass_temporalPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_temporalPFI.py
    - name: args_lda_nn_fe_multiclass_temporospectralPFI
      run: |
        cp examples/args_lda_nn_fe_multiclass_temporospectralPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_temporospectralPFI.py
    
