# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: module tests
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        which python
        python -m pytest module_tests/*

    - name: Get data
      run: |
        cp -r /well/woolrich/users/yaq921/MEG-transfer-decoding/data data

    - name: args_lda_pca_fe_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_pca_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_pca_fe_multiclass.py
    - name: args_lda_pca_sw_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_pca_sw_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_pca_sw_multiclass.py
    - name: args_cichy92_lda_pca_fe_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_cichy92_lda_pca_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_cichy92_lda_pca_fe_multiclass.py
    - name: args_nn
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_nn.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_nn.py
    - name: args_lda_nn_chn_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_chn_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_chn_multiclass.py
    - name: args_lda_nn_fe_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass.py
    - name: args_lda_nn_sw_multiclass
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_sw_multiclass.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_sw_multiclass.py
    - name: args_lda_nn_fe_multiclass2pairwise
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass2pairwise.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass2pairwise.py
    - name: args_lda_nn_fe_multiclass_spatialPFI
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass_spatialPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spatialPFI.py
    - name: args_lda_nn_fe_multiclass_spatiotemporal
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass_spatiotemporal.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spatiotemporal.py
    - name: args_lda_nn_fe_multiclass_spectralPFI
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass_spectralPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_spectralPFI.py
    - name: args_lda_nn_fe_multiclass_temporalPFI
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass_temporalPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_temporalPFI.py
    - name: args_lda_nn_fe_multiclass_temporospectralPFI
      run: |
        source ~/.condasetup
        module load Anaconda3
        conda activate job_run
        cp examples/args_lda_nn_fe_multiclass_temporospectralPFI.py args.py
        taskset --cpu-list 12-23 python launch.py
        python tests/test_lda_nn_fe_multiclass_temporospectralPFI.py
    
